### ISSUE TITLE
Error While Filling Out Email

### ISSUE THREAD

**Issue by cChimney** [Alkosik/Discord-Alt-Token-Generator#3]
Bot initialized succesfully - Alkosik
LINE:0
alkos
+0@gmail.com
CURRENT MAILS:1
Traceback (most recent call last):
  File "C:\Users\User\Desktop\discord-alt-token-generator-master\generator.py", line 413, in <module>
    account = current_bot.generate_token()
  File "C:\Users\User\Desktop\discord-alt-token-generator-master\generator.py", line 87, in generate_token
    account = self.register_account()
  File "C:\Users\User\Desktop\discord-alt-token-generator-master\generator.py", line 163, in register_account
    email_textbox = self.driver.find_elements_by_css_selector(
IndexError: list index out of range

Getting that error and i have no idea how to fix it

**Comment by Alkosik** [comment]
I got it fixed. Just re-download the script and try again.
